### ISSUE TITLE
Support loading string from ResX

### ISSUE THREAD

**Issue by frg2089** [dotmake-build/command-line#9]
### Could we support some one that can be used for i18n?
Such as [`System.ComponentModel.DataAnnotations.DisplayAttribute.ResourceType`](https://learn.microsoft.com/dotnet/api/system.componentmodel.dataannotations.displayattribute.resourcetype)

When I make an i18n app using ResX, I got an error `CS0182`.
```csharp
[CliCommand(Description = Resource.CommandDescription)]
internal sealed class Command
{
    // ...
}
```

**Comment by calacayir** [comment]
FYI, this feature is now ready in v1.6.9:

- Added support for localizing commands, options and arguments.
  You can now specify a `nameof` operator expression with a resource property (generated by resx) in the attribute's argument (for `string` types only)
  and the source generator will smartly use the resource property accessor as the value of the argument so that it can localize at runtime.
  If the property in the `nameof` operator expression does not point to a resource property, then the name of that property will be used as usual.
```c#
[CliCommand(Description = nameof(TestResources.CommandDescription))]
internal class LocalizedCliCommand
{
    [CliOption(Description = nameof(TestResources.OptionDescription))]
    public string Option1 { get; set; } = "DefaultForOption1";

    [CliArgument(Description = nameof(TestResources.ArgumentDescription))]
    public string Argument1 { get; set; }

    public void Run()
    {
        Console.WriteLine($@"Handler for '{GetType().FullName}' is run:");
        Console.WriteLine($@"Value for {nameof(Option1)} property is '{Option1}'");
        Console.WriteLine($@"Value for {nameof(Argument1)} property is '{Argument1}'");
        Console.WriteLine();
    }
}
```
